### ISSUE TITLE
App creates duplicate chatterm.db and debug.log files.

### ISSUE THREAD

**Issue by LostinTimeandspaceYT** [zigzter/chatterm#5]
I created an alias in my `.zshrc` 

```
alias chatterm='~/chatterm/chatterm'
```

and it works but it creates a `chatterm.db` and `debug.log` file inside the directory that invokes `chatterm`.

 Is there anyway to have it so it points to the same `.db` and `.log` file rather than creating new ones in each directory?

**Comment by zigzter** [comment]
@LostinTimeandspaceYT I think I see why, I'll get a fix up soon! :pray:

**Comment by zigzter** [comment]
@LostinTimeandspaceYT Should be fixed now! Let me know if it isn't.
