### ISSUE TITLE
Authorizing page gives a 404 not found

### ISSUE THREAD

**Issue by fluffydarknergoat** [zigzter/chatterm#7]
so yeah - as the title says, I'm trying to authorize the use of chatterm, and the localhost page is giving me a 404 page not found error every time I try. it was perfectly fine the last time I did this, and everything worked just fine when I briefly gave Chatterino a try, so I don't know what's going on here.

**Comment by fluffydarknergoat** [comment]
> @fluffydarknergoat do you happen to have anything else running on `localhost:3030`? I went to check myself and forgot I had a Rails server running on that port which stopped the auth process. What happens if you load `localhost:3030` directly in your browser?

getting a unable to connect error

**Comment by zigzter** [comment]
Hmm that's odd. What's the URL that gives the 404? If you remove the connection in [Twitch Settings](https://www.twitch.tv/settings/connections) and retry, does it still happen?

**Comment by fluffydarknergoat** [comment]
> Hmm that's odd. What's the URL that gives the 404? If you remove the connection in [Twitch Settings](https://www.twitch.tv/settings/connections) and retry, does it still happen? (Should be listed as "Terminal Chat App")

yeah - I've removed and re-added the connection multiple times now, and it still happens. 

as far at the URL, it's http://localhost:3030/#access_token=fqzrofomwdxspayoura5e80as35djq&scope=chat%3Aread+chat%3Aedit+user%3Aread%3Achat+user%3Aread%3Afollows+user%3Aread%3Asubscriptions+channel%3Amoderate+moderator%3Amanage%3Achat_messages+moderator%3Amanage%3Abanned_users+moderator%3Aread%3Afollowers&state=45B8C9F8E11E35CF0C23&token_type=bearer

**Comment by zigzter** [comment]
Does `cat ~/.config/chatterm/debug.log` print anything? Are you on the latest git commit?

**Comment by fluffydarknergoat** [comment]
> Does `cat ~/.config/chatterm/debug.log` print anything? Are you on the latest git commit?

yep! I've been trying to use the latest release. downloaded the binary, clone it with Go, both ways don't work.

and all debug.log says is 'debug 2024/07/15 10:54:14 Config file not found, creating a new one...' , and the only thing that does is generate a .json file. no folder or anything is created.
